version: '2'

services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - 80:8080
    restart: always
    environment:
    - JAVA_OPTS=
        -Djenkins.install.runSetupWizard=false
        -Djava.awt.headless=true
    volumes:
      - 'jenkins-data:/var/jenkins_home'
    logging:
      driver: journald
      options:
        tag: docker-jenkins
    ulimits:
      nproc: 65535
      nofile:
        soft: 20000
        hard: 40000

  nexus:
    image: sonatype/nexus3
    ports:
      - 8081:8081
    restart: always
    volumes:
      - 'nexus-data:/nexus-data'

volumes:
  jenkins-data:
  nexus-data:
